mes-journal-schema/package.json, mes-test-schema/.gitignore, mes-test-schema/categories/schema-category-B.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Very very rough stab at test schema for standard category B car tests. This will evolve dramatically over time. 
- Creates a `categories` directory in anticipation of having a schema for each test category.
=> Adds preliminary cat b test schema

mes-test-schema/package.json
Forgot to bump the version in #3 - bring on the automation! 😁
=> Bump version to 1.0.1 for test schema

mes-test-schema/categories/schema-category-B.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
* Decouple the domain concept of pre-test declarations from the waiting room screen
* Ensure that TS generation is only a devDependency
=> Remove preTest intermediary property in cat B schema

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json
Contains all data items recorded E2E
=> Test Schema for Category B

mes-journal-schema/package.json, mes-journal-schema/schema-examiner-work-schedule.json
Change 'checkDigits' to 'checkDigit'
=> Update to checkDigit in journal schema

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Add D255, debriefWitnessed, identification.  Remove required items as page can be saved without being complete.
=> Test schema changes for Office page

.gitignore, openapi.yaml, package-lock.json, package.json
* Created OpenAPI definition for the Initial Journal Only release REST API operations.
* Added speccy, run ```npm run check``` to lint the definition. Also manually tested the file in the Swagger editor (https://editor.swagger.io)
* Since Swagger/OpenAPI doesn't support recent JSON Schema, and speccy.io doesn't seem to support converting complex JSON schema to OpenAPI schema format (defect raised with them, see https://github.com/wework/speccy/issues/308), any complex types have been replaced by a _Dummy_ schema object
- [*] [WIP] tag removed from PR title
- [*] PR has an understandable description
- [*] branch name comply with our branching strategy
- [*] git branch contains relevant JIRA ticket number
- [*] branch rebased against the latest develop
- [*] Code has been tested manually
=> Added Initial OpenAPI definition

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Changing the VehicleChecks property of the TestData.
=> MES-2186 Refactor the vehicle checks schema

mes-test-schema/categories/B/index.d.ts, mes-test-schema/package-lock.json, mes-test-schema/package.json
Was a typo, now it's corrected.
=> correcting typo

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> Add comments to manoeuvre faults

mes-test-schema/categories/schema-core-definitions.json
Add "$id" key value to allow external references
Add more commonly referenced keys to schema
=> Prep work to enable external references to common schema

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Add communicationPreferences object
=> Add communication preferences to Cat B schema

mes-journal-schema/package-lock.json, mes-journal-schema/package.json, mes-journal-schema/schema-examiner-work-schedule.json
=> Add vehicle slot type

mes-journal-schema/package-lock.json, mes-journal-schema/package.json
=> Increment journal schema patch version for publishing

mes-journal-schema/Journal.d.ts, mes-journal-schema/package-lock.json, mes-journal-schema/package.json, mes-journal-schema/schema-examiner-work-schedule.json
Add specialNeedsExtendedTest
Add specialNeedsCode
=> Add special needs fields to centralised Journal schema

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Add "N/A" option to independentDriving enum
=> Add N/A option to independentDriving

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Adding 'conductedLanguage' type to JSON schema. This will be used to capture how the candidate wishes to progress the test (in English or Welsh) on the Communication Capture Page.
=> MES-2265: Incorporating conducted language of test

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
* Test centre ID is required as it is saved in Aurora
* Expanding the test schema to require this property
=> MES-2995: Capture the test centre ID in the test schema

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> MES-2310 Add Show Me Tell Me Comments

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> Remove ID from test schema

mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Changing min/max-length of start date to 19
=> Changing start min/max-length to 19

mes-journal-schema/schema-examiner-work-schedule.json
* Equivalent change to #36, but in journal schema
=> Ensure journal slot start is 19 chars, not 25

mes-journal-schema/package-lock.json, mes-journal-schema/package.json
=> Bump version to 1.0.5

mes-search-schema/package.json
=> Changed version to 1.0.0

mes-search-schema/index.d.ts, mes-search-schema/index.json, mes-search-schema/package-lock.json, mes-search-schema/package.json
=> Change staff number to driverNumber, and incremented version number

mes-test-schema/categories/B/index.json, package-lock.json, package.json
Adding maximum length limit of 1000 characters to all `faultComments` and `candidateDescription`
=> MES-2939: Adding max length limit

mes-test-schema/package-lock.json, mes-test-schema/package.json
Just adding a new version number.
=> Patching new version number

mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Adding max length constraint to `passCertificateNumber`
=> MES-2948: adding max length constraint to pass cert

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json, package-lock.json, package.json
Adding extra field for supporting the Search Result View
- test centre name
- special needs code
- entitlement check
- precious cancellations
=> MES-2938: Adding a few extra properties

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Pre-requisite for https://github.com/dvsa/mes-mobile-app/pull/603
=> MES-2994: Add eyesightTest to serious faults

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
adding special needs array
adding slot type
=> MES-2938: Adding extra fields

mes-journal-schema/Journal.d.ts, mes-journal-schema/package-lock.json, mes-journal-schema/package.json, mes-journal-schema/schema-examiner-work-schedule.json
Change to personal commitment to remove start date and time, end date and time and to add slotId instead.
=> Feature mes 3086 update journal schema for personal commitment

mes-test-schema/categories/B/index.json, mes-test-schema/package.json
- Added maxLength properties to the instructor number and vehicle reg in the test json schema
- Ran json2ts on the `index.json` but it didn't make any changes to the `indes.d.ts`
=> Mes 3101 & 3109 - wrtc field length validation

mes-journal-schema/Journal.d.ts, mes-journal-schema/package-lock.json, mes-journal-schema/package.json, mes-journal-schema/schema-examiner-work-schedule.json
Re added startDate, startTime, endDate and endTime to remain backwardly compatible.
=> re-add removed fields for backward compatibility

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Changed the examiner keyed field from a boolean to a number
=> MES-2022 - Fixed examiner keyed field

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package.json
Replication of [PR 69](https://github.com/dvsa/mes-api-definitions/pull/60) for merging into release 2.0
=> MES-3111 - Fix for when terminating test on CCP page... for release-2.0

mes-config-schema/mdm-config.d.ts, mes-config-schema/mdm-config.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
Removing some fields & setting some fields optional to make sure that the properties align.
=> MES-3534: Removing some fields and also setting some others optional

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
- Changed Permisssions to Permissions
=> MES-3534 - Fixed Typo in schema

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
Making `to` property required but nullable
=> Mes 3534 updating some fields

mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Adding min length check to passCertificateNumber to ensure it is exactly 8 characters
Story: https://jira.dvsacloud.uk/browse/MES-3185
=> mes-3185 - adding min length of pass cert number

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
- Fixing a TODO left by MES-2788
- Adds a configurable key for the examiner name in the app config
=> MES-2788 - Added examiner name key to app config

mes-test-schema/categories/B/index.json, mes-test-schema/package.json
Cherry pick https://github.com/dvsa/mes-api-definitions/pull/68 schema changes into `release-2.0-hotfix1`
=> mes-3185 - cherry-pick pass cert schema changes

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
=> MES-2788 - Make employee name key required

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Adds a new 'version' property for the schema
https://jira.dvsacloud.uk/browse/MES-3632
=> Mes 3632 add version number to test result data

mes-test-schema/package-lock.json, mes-test-schema/package.json
=> Bumping minor version number

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/B/index.json, mes-test-schema/categories/B/partial.d.ts, mes-test-schema/categories/B/partial.json, mes-test-schema/categories/BE/index.d.ts, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/BE/partial.d.ts, mes-test-schema/categories/BE/partial.json, mes-test-schema/categories/Common/index.d.ts, mes-test-schema/categories/Common/index.json, mes-test-schema/categories/index.d.ts, mes-test-schema/categories/test.ts, mes-test-schema/generateSchemas.ts, mes-test-schema/package.json
- Implementing Common JSON to match required typescript types
- Implementing Cat B Partial JSON to match required typescript types
- Implementing Cat BE Partial JSON to match required typescript types
- Creating `CatBUnique` namespace to export category specific types
- Creating `CatBEUnique` namespace to export category specific types
=> Mes 3798 cat unique namespaces

mes-test-schema/package-lock.json, mes-test-schema/package.json, package-lock.json, package.json
=> Bump version 3.2.1

mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/Common/index.d.ts, mes-test-schema/categories/Common/index.json, mes-test-schema/categories/index.d.ts, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Adds `testRequirements` to the `TestData` interface in the common schema
- Removes intersection types, imports correct category schemas for union
- Removes `faultSummary` as it is not used
=> Mes 3384 schema updates multi category

mes-test-schema/categories/BE/index.json, mes-test-schema/categories/BE/partial.d.ts, mes-test-schema/categories/BE/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Updating JournalData and Candidate properties to be required in cat b+e schema
=> Making JournalData & Candidate required in cat b+e

mes-test-schema/categories/B/index.json, mes-test-schema/categories/B/partial.d.ts, mes-test-schema/categories/B/partial.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/BE/partial.d.ts, mes-test-schema/categories/BE/partial.json, mes-test-schema/categories/Common/index.d.ts, mes-test-schema/categories/Common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Extracting Manoeuvre definition into common and using it in cat-b cat-be partials
=> MES-3833: Extracting Manoeuvre definition into common

mes-test-schema/categories/index.d.ts, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Removing `PassCompletion` from `BE/partials` as this is now common between both categories.
=> MES-4239: Removing pass completion for B+E schema

README.md
- Adds process steps for how to update a schema
Markdown Preview -
=> Updates readme with "Updating a schema" section

mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Adds "Diagram" to permitted values for independent driving.
- Bump version number
=> Mes 4245 update independent driving enum to include 'Diagram'

mes-test-schema/categories/BE/partial.d.ts, mes-test-schema/categories/BE/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> MES-4311 - Added Vehicle Details to Partial B+E Schema

mes-test-schema/categories/C/index.d.ts, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C/partial.d.ts, mes-test-schema/categories/CE/index.d.ts, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/CE/partial.d.ts, mes-test-schema/category-definitions/C/partial.json, mes-test-schema/category-definitions/CE/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Union type for pass completion.
=> Pass completion union type for cat C and cat CE

mes-test-schema/categories/B/index.d.ts, mes-test-schema/package-lock.json, mes-test-schema/package.json
Vehicle details union type for cat B.
=> Added vehicle details union type for cat B

mes-test-schema/package-lock.json, mes-test-schema/package.json
- Updates the version of the npm package to 3.8.0
=> MES-4283 - Publish Cat C Subtype Schemas

mes-test-schema/categories/B/index.d.ts, mes-test-schema/categories/BE/index.d.ts, mes-test-schema/package-lock.json, mes-test-schema/package.json
Added pass completion to B and BE unique types.
=> Added passCompletion to catB and catBE namespaces

mes-test-schema/categories/D/index.d.ts, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D/partial.d.ts, mes-test-schema/categories/D1/index.d.ts, mes-test-schema/categories/D1E/index.d.ts, mes-test-schema/categories/DE/index.d.ts, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/DE/partial.d.ts, mes-test-schema/category-definitions/D/partial.json, mes-test-schema/category-definitions/DE/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Adding pass completion to Cat D and DE that only contains code78.
=> Adding pass completion to cat D and DE

mes-test-schema/categories/index.d.ts, mes-test-schema/package-lock.json, mes-test-schema/package.json
Cat Ds to TestResultSchemasUnion
=> Adding cat Ds to TestResultSchemasUnion type

mes-test-schema/categories/D/index.d.ts, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D/partial.d.ts, mes-test-schema/categories/D1/index.d.ts, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1/partial.d.ts, mes-test-schema/categories/D1E/index.d.ts, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/D1E/partial.d.ts, mes-test-schema/categories/DE/index.d.ts, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/DE/partial.d.ts, mes-test-schema/category-definitions/D/partial.json, mes-test-schema/category-definitions/D1/partial.json, mes-test-schema/category-definitions/D1E/partial.json, mes-test-schema/category-definitions/DE/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Restructure safety question so they mirror vehicle checks implementation.
Update from the original schema creation for CAT D as part of https://jira.dvsacloud.uk/browse/MES-4307
=> restructure safety questions

mes-test-schema/categories/D/index.json, mes-test-schema/categories/D/partial.d.ts, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1/partial.d.ts, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/D1E/partial.d.ts, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/DE/partial.d.ts, mes-test-schema/category-definitions/D/partial.json, mes-test-schema/category-definitions/D1/partial.json, mes-test-schema/category-definitions/D1E/partial.json, mes-test-schema/category-definitions/DE/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Updated the PCV Door Exercise Schema
=> MES-4129  - PCV Door Exercise Schema Update

mes-config-schema/mdm-config.d.ts, mes-config-schema/mdm-config.json
=> feat: add new flag to allow local-storage rehydration plugin to be conditionally enabled

mes-config-schema/package-lock.json, mes-config-schema/package.json
Local testing successfully completed in browser and on iPad with `npm link`ed module.
=> chore: version bump

mes-test-schema/categories/AM2/index.d.ts, mes-test-schema/categories/AM2/index.json, mes-test-schema/category-definitions/AM2/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
mes-5008 Added new fields to schema for mod2 including test conducted on and safety and balance comments
=> mes-5008 Added new fields to schema for mod2

mes-test-schema/categories/AM1/index.json, mes-test-schema/category-definitions/AM1/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Changing pass certificate number to 7 character long
=> MES-5005: Changing pass certificate number to 7 characters

mes-test-schema/categories/index.d.ts, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> Added union type for home tests

mes-test-schema/categories/ADI2/index.d.ts, mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/ADI2/partial.d.ts, mes-test-schema/category-definitions/ADI2/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
ADI2 have two manoeuvres, these have been combined to an array of manoeuvers
=> ADI2 Manoeuvres refactor MES-4821

mes-test-schema/categories/ADI2/index.d.ts, mes-test-schema/package-lock.json, mes-test-schema/package.json
The wrong type was exported in the CatADI2UniqueTypes
=> Wrong exported type in CatADI2UniqueTypes mes-4821

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/ADI2/partial.d.ts, mes-test-schema/category-definitions/ADI2/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
MES-4821 show me questions were missed from the schema
=> Added show me questions for adi2

mes-test-schema/categories/F/index.json, mes-test-schema/categories/F/partial.d.ts, mes-test-schema/categories/G/index.json, mes-test-schema/categories/G/partial.d.ts, mes-test-schema/categories/H/index.json, mes-test-schema/categories/H/partial.d.ts, mes-test-schema/categories/K/index.json, mes-test-schema/categories/K/partial.d.ts, mes-test-schema/category-definitions/F/partial.json, mes-test-schema/category-definitions/G/partial.json, mes-test-schema/category-definitions/H/partial.json, mes-test-schema/category-definitions/K/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
MES 5015
Small change to schema for F, G, H and K to add selected (used to show green tick).
- [] Tested by QA
=> add selected to highwayCodeSafety

mes-test-schema/package-lock.json, mes-test-schema/package.json
=> MES-503 - Bumps version for ADI2 Vehicle checks

mes-search-schema/index.d.ts, mes-search-schema/index.json, mes-search-schema/package-lock.json, mes-search-schema/package.json
- Adds activity code 6 to search schema
=> MES-5173 add activity code 6 to search schema

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Adds 5 new competencies for cat a mod 2
=> mes-5179 add 5 new faults for cat a mod 2

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/AM2/index.d.ts, mes-test-schema/categories/AM2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/AM2/index.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- move new competencies to Mod2 specific schema
=> mes-5179 adds 5 new faults for cat a mod 2

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/ADI2/partial.d.ts, mes-test-schema/category-definitions/ADI2/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
VehicleChecksCompleted field added to test schema.
=> MES-5219 Vehicle Checks Completed added

mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/category-definitions/CPC/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Add combination codes type instead of generic string, remove weather conditions from the schema
=> MES-5321 / Cat CPC Schema update

mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/category-definitions/CPC/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
update validation for pass certificate and don't mandate gearbox
=> MES-2671 / CPC schema change

mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/category-definitions/CPC/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
remove required from registrationNumber and configuration which might not have values for terminated tests
=> MES-2671 / Schema change for terminated CPC tests

mes-test-schema/categories/BE/index.json, mes-test-schema/categories/BE/partial.d.ts, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C/partial.d.ts, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1/partial.d.ts, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/C1E/partial.d.ts, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/CE/partial.d.ts, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D/partial.d.ts, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1/partial.d.ts, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/D1E/partial.d.ts, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/DE/partial.d.ts, mes-test-schema/category-definitions/BE/partial.json, mes-test-schema/category-definitions/C/partial.json, mes-test-schema/category-definitions/C1/partial.json, mes-test-schema/category-definitions/C1E/partial.json, mes-test-schema/category-definitions/CE/partial.json, mes-test-schema/category-definitions/D/partial.json, mes-test-schema/category-definitions/D1/partial.json, mes-test-schema/category-definitions/D1E/partial.json, mes-test-schema/category-definitions/DE/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Add vehicle checks completed flag for cats: BE, C, C1, C1E, CE, D, D1, D1E, DE
=> MES-5324 / Vehicle Checks Completed

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
Add DLG to examiner role type definition
=> MES-5427 / DLG Examiner role

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/CPC/index.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package.json
Add optional candidateDeclarationSigned to preTestDeclarations to be used in delegated tests
=> Candidate Declaration Signed

README.md, mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/AM1/index.d.ts, mes-test-schema/categories/AM1/index.json, mes-test-schema/categories/AM2/index.d.ts, mes-test-schema/categories/AM2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
https://jira.dvsacloud.uk/browse/MES-5793
Update schema to allow test centre to be optional to allow delEx tests to go through to test results db
=> Mes-5793: change test centre to be optional 

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
=> MES-5346L: Adds delegated examiner search url key

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/AM1/index.d.ts, mes-test-schema/categories/AM1/index.json, mes-test-schema/categories/AM2/index.d.ts, mes-test-schema/categories/AM2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> MES-5790: Makes test centre required

mes-test-schema/categories/D/index.d.ts, mes-test-schema/categories/D1/index.d.ts, mes-test-schema/categories/D1E/index.d.ts, mes-test-schema/categories/DE/index.d.ts, mes-test-schema/package-lock.json, mes-test-schema/package.json
Removing safety questions from the unique types on cat Ds
Bumping version number
=> Mes 6085 remove safety questions unique types

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.json
- Remove logs prop from required array in config-schema
=> MES-6608 / Remove logs as a required property

mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
- Adds optional property for team journal url.
=> MES-6561 Add new property for team journal url

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/AM1/index.d.ts, mes-test-schema/categories/AM1/index.json, mes-test-schema/categories/AM2/index.d.ts, mes-test-schema/categories/AM2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/AM1/index.json, mes-test-schema/category-definitions/AM2/index.json, mes-test-schema/category-definitions/CPC/index.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Add app version as an optional key to all categories
=> MES-6833 / App Version key

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D/partial.d.ts, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1/partial.d.ts, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/D1E/partial.d.ts, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/DE/partial.d.ts, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/D/partial.json, mes-test-schema/category-definitions/D1/partial.json, mes-test-schema/category-definitions/D1E/partial.json, mes-test-schema/category-definitions/DE/partial.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Revert safetyQuestion schema changes from test-schema
=> Revert SafetyQuestion changes from develop

mes-test-schema/categories/D/index.d.ts, mes-test-schema/categories/D1/index.d.ts, mes-test-schema/categories/D1E/index.d.ts, mes-test-schema/categories/DE/index.d.ts, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> Add safety questions to Unique types for Cat D

mes-config-schema/mdm-config.d.ts, mes-config-schema/mdm-config.json, mes-config-schema/package.json
- Adds optional properties to MDM config for Sentry integration (will be required for DES 4 but not 3)
=> MES-6955 Add sentry to config

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/AM1/index.d.ts, mes-test-schema/categories/AM1/index.json, mes-test-schema/categories/AM2/index.d.ts, mes-test-schema/categories/AM2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/AM1/index.json, mes-test-schema/category-definitions/AM2/index.json, mes-test-schema/category-definitions/CPC/index.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Add new 'trueLikenessToPhoto' property to testSummary object
=> MES-7534 / True likeness to photo

mes-test-schema/categories/C1EM/index.json, mes-test-schema/categories/C1EM/partial.d.ts, mes-test-schema/categories/C1M/index.json, mes-test-schema/categories/C1M/partial.d.ts, mes-test-schema/categories/CEM/index.json, mes-test-schema/categories/CEM/partial.d.ts, mes-test-schema/categories/CM/index.json, mes-test-schema/categories/CM/partial.d.ts, mes-test-schema/categories/D1EM/index.json, mes-test-schema/categories/D1EM/partial.d.ts, mes-test-schema/categories/D1M/index.json, mes-test-schema/categories/D1M/partial.d.ts, mes-test-schema/categories/DEM/index.json, mes-test-schema/categories/DEM/partial.d.ts, mes-test-schema/categories/DM/index.json, mes-test-schema/categories/DM/partial.d.ts, mes-test-schema/category-definitions/C1EM/partial.json, mes-test-schema/category-definitions/C1M/partial.json, mes-test-schema/category-definitions/CEM/partial.json, mes-test-schema/category-definitions/CM/partial.json, mes-test-schema/category-definitions/D1EM/partial.json, mes-test-schema/category-definitions/D1M/partial.json, mes-test-schema/category-definitions/DEM/partial.json, mes-test-schema/category-definitions/DM/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Add vehicle height to manoeuvre schemas
=> MES-7548 / WRTC manoeuvre schema addition

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/C1EM/index.json, mes-test-schema/categories/C1M/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/CEM/index.json, mes-test-schema/categories/CM/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/D1EM/index.json, mes-test-schema/categories/D1M/index.json, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/DEM/index.json, mes-test-schema/categories/DM/index.json, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Make provisional licence received optional
=> MES-7569 / Make Provisional licence optional

mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1/partial.d.ts, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/C1E/partial.d.ts, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1/partial.d.ts, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/D1E/partial.d.ts, mes-test-schema/category-definitions/C1/partial.json, mes-test-schema/category-definitions/C1E/partial.json, mes-test-schema/category-definitions/D1/partial.json, mes-test-schema/category-definitions/D1E/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Add code 78 to C1, C1+E, D1 and D1+E
=> Standardise Code 78

mes-test-schema/categories/D/index.d.ts, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D/partial.d.ts, mes-test-schema/categories/D1/index.d.ts, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1/partial.d.ts, mes-test-schema/categories/D1E/index.d.ts, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/D1E/partial.d.ts, mes-test-schema/categories/DE/index.d.ts, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/DE/partial.d.ts, mes-test-schema/category-definitions/D/partial.json, mes-test-schema/category-definitions/D1/partial.json, mes-test-schema/category-definitions/D1E/partial.json, mes-test-schema/category-definitions/DE/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> Cat D  - Manoeuvres pass cert

mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/category-definitions/CPC/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> mes-8030: (3.38.3) update cpc category to make combination and score optional

mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/category-definitions/CPC/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> mes-8030: remove required items from question and question5

package-lock.json, package.json
=> mes8056 audit fixes

mes-search-schema/index.d.ts, mes-search-schema/index.json, mes-search-schema/package-lock.json, mes-search-schema/package.json
=> MES-8002 | Added grade to search-schema

mes-test-schema/categories/ADI3/index.d.ts, mes-test-schema/categories/ADI3/index.json, mes-test-schema/category-definitions/ADI3/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> Make pass cert optional in schema for ADI3

mes-test-schema/categories/ADI3/index.d.ts, mes-test-schema/categories/ADI3/index.json, mes-test-schema/category-definitions/ADI3/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> added d255 to adi-3 schema

mes-test-schema/categories/ADI3/index.d.ts, mes-test-schema/categories/ADI3/index.json, mes-test-schema/category-definitions/ADI3/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> MES-8245 / Update ADI3 schema to cater for SC

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
=> MES-8255 / Driver URLs

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/AM2/index.d.ts, mes-test-schema/categories/AM2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/C1EM/index.json, mes-test-schema/categories/C1M/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/CEM/index.json, mes-test-schema/categories/CM/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/D1EM/index.json, mes-test-schema/categories/D1M/index.json, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/DEM/index.json, mes-test-schema/categories/DM/index.json, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
Added new eco fields to common eco interface MES-8240
=> MES-8240 ECO fields

mes-config-schema/mdm-config.d.ts, mes-config-schema/mdm-config.json, mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
- Add tax and mot URL to config schema
- Add taxMot api key prop to mdm config
- Make driver property optional;
=> MES-8311 / Tax and MOT

mes-test-schema/categories/ADI2/index.json, mes-test-schema/categories/B/index.json, mes-test-schema/categories/BE/index.json, mes-test-schema/categories/C/index.json, mes-test-schema/categories/C1/index.json, mes-test-schema/categories/C1E/index.json, mes-test-schema/categories/C1EM/index.json, mes-test-schema/categories/C1M/index.json, mes-test-schema/categories/CE/index.json, mes-test-schema/categories/CEM/index.json, mes-test-schema/categories/CM/index.json, mes-test-schema/categories/D/index.json, mes-test-schema/categories/D1/index.json, mes-test-schema/categories/D1E/index.json, mes-test-schema/categories/D1EM/index.json, mes-test-schema/categories/D1M/index.json, mes-test-schema/categories/DE/index.json, mes-test-schema/categories/DEM/index.json, mes-test-schema/categories/DM/index.json, mes-test-schema/categories/F/index.json, mes-test-schema/categories/G/index.json, mes-test-schema/categories/H/index.json, mes-test-schema/categories/K/index.json, mes-test-schema/categories/common/index.d.ts, mes-test-schema/categories/common/index.json, mes-test-schema/category-definitions/common/index.json, mes-test-schema/package.json
=> mes-529: add motStatus to vehicle details as an option field

mes-test-schema/package-lock.json
=> Update lock file

mes-journal-schema/index.d.ts, mes-journal-schema/index.json, mes-journal-schema/package-lock.json, mes-journal-schema/package.json
Added new fitMarker property to application interface
=> MES-8363 | FIT marker

mes-search-schema/index.d.ts, mes-search-schema/index.json, mes-search-schema/package-lock.json, mes-search-schema/package.json
- Add new code to search schema AC list
=> MES-8614 / Code88 to Search Schema

.github/workflows/publish.yaml
=> Amend flow to use GH token

.github/workflows/publish.yaml
=> Testing turbolift

.github/workflows/publish.yaml
=> Update Publish flow

mes-test-schema/package-lock.json, mes-test-schema/package.json
=> mes-8482: version bump

mes-test-schema/package-lock.json, mes-test-schema/package.json
Reverts dvsa/mes-api-definitions#283
=> Revert "mes-8482: version bump"

.github/workflows/publish.yaml, mes-test-schema/categories/C1EM/partial.d.ts, mes-test-schema/categories/C1M/partial.d.ts, mes-test-schema/categories/CEM/partial.d.ts, mes-test-schema/categories/CM/partial.d.ts, mes-test-schema/categories/D1EM/partial.d.ts, mes-test-schema/categories/D1M/partial.d.ts, mes-test-schema/categories/DEM/partial.d.ts, mes-test-schema/categories/DM/partial.d.ts, mes-test-schema/category-definitions/C1EM/partial.json, mes-test-schema/category-definitions/C1M/partial.json, mes-test-schema/category-definitions/CEM/partial.json, mes-test-schema/category-definitions/CM/partial.json, mes-test-schema/category-definitions/D1EM/partial.json, mes-test-schema/category-definitions/D1M/partial.json, mes-test-schema/category-definitions/DEM/partial.json, mes-test-schema/category-definitions/DM/partial.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
- Add MOT fields to Vehicle details Manoeuvres schema(s)
=> Update workflow type to be a choice rather than a string

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
- Add property for holding the liveAppVersion
=> MES-8914 / Live app version

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
- Add flag for the disabling of SAM
=> Config Schema: Flag to enable ASAM

README.md
changed readme to include config
=> mes-readMeUpdate

mes-search-schema/index.d.ts, mes-search-schema/index.json, mes-search-schema/package-lock.json, mes-search-schema/package.json
To allow distinction of the status of a test being uploaded, autosave has been added
=> MES-9554: add autosave to results interface

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
=> add new url for mot history

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
add url to requesting multiple test results as a batch.  Added as optional to allow other features to be developed alongside.
=> MES-9817-multiple-test-results url

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
make obsolete entry optional so allow old versions to still function
=> mes-9495: Decomission UA key

mes-search-schema/index.d.ts, mes-search-schema/index.json, mes-search-schema/package.json
=> add code 89 to search schema

mes-test-schema/categories/ADI3/index.d.ts, mes-test-schema/categories/ADI3/index.json, mes-test-schema/categories/AM1/index.d.ts, mes-test-schema/categories/AM1/index.json, mes-test-schema/categories/AM2/index.d.ts, mes-test-schema/categories/AM2/index.json, mes-test-schema/categories/CPC/index.d.ts, mes-test-schema/categories/CPC/index.json, mes-test-schema/category-definitions/ADI3/index.json, mes-test-schema/category-definitions/AM1/index.json, mes-test-schema/category-definitions/AM2/index.json, mes-test-schema/category-definitions/CPC/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> feat (mes-10059): expand userExitedApp to bespoke categories

mes-test-schema/categories/AM2/index.d.ts, mes-test-schema/categories/AM2/index.json, mes-test-schema/category-definitions/AM2/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json
=> feat (mes-10059): update AM2

mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json, package-lock.json
=> mes-9245: add section for useful links

mes-config-schema/package-lock.json, mes-config-schema/package.json, mes-config-schema/remote-config.d.ts, mes-config-schema/remote-config.json
=> feat (mes-9245): useful links change to array

.github/workflows/publish.yaml, mes-config-schema/.npmrc, mes-config-schema/package.json, mes-driver-schema/.npmrc, mes-driver-schema/package.json, mes-journal-schema/.npmrc, mes-journal-schema/package.json, mes-mot-schema/.npmrc, mes-mot-schema/package.json, mes-search-schema/.npmrc, mes-search-schema/package.json, mes-test-schema/.npmrc, mes-test-schema/package.json
=> feat: move from internal to npm

mes-journal-schema/package.json
=> feat: remove redundent test command that is blocking publish

mes-mot-schema/index.d.ts, mes-mot-schema/index.json, mes-mot-schema/package-lock.json, mes-mot-schema/package.json
=> chore: mot as types

mes-test-schema/categories/ADI3/index.d.ts, mes-test-schema/categories/ADI3/index.json, mes-test-schema/category-definitions/ADI3/index.json, mes-test-schema/package-lock.json, mes-test-schema/package.json, package.json
Add variables to represent whether or not a variable is too short in SC
=> mes-addShortTestToSC
