dvsa/mes-api-definitions

mes-test-schema/categories/schema-category-B.json

* Ensure that we publish the cat B types to npm via `.npmignore`
* Extract type for `TestData`
* Generate the following new interfaces:
```
/**
* Data related to the test phase prior to the test report
*/
export interface PreTest {
waitingRoom: WaitingRoom;
}
export interface WaitingRoom {
/**
* Whether or not the candidate has declared that their test vehicle has a valid insurance policy
*/
insuranceDeclarationAccepted: boolean;
/**
* Whether or not the candidate has declared that they have lived in the UK for a period acceptable for taking the test
*/
residencyDeclarationAccepted: boolean;
/**
* Base 64 encoded binary data representing a PNG image of the candidates signature
*/
signature: string;
}
```

MES-995: Add preTest + waitingRoom to the cat B schema

---

mes-test-schema/categories/B/index.json

Removed instructor certification number
Removed testOutcome as it's covered by activityCode
Added passCertificateNumberReceived
Other minor tweaks

Ongoing changes to CatB test schema

---

mes-test-schema/categories/B/index.d.ts
mes-test-schema/package.json

* Generate TypeScript definitions missed in previous check-in
* Complete cat B full journey, including post-test
* Refactor how faults and other test related data is stored
* Removed mandatory restrictions on several items to accommodate terminations
* Extract additional types for usage in the mobile app

Publish test schema v1.0.4

---

mes-test-schema/categories/B/index.d.ts
mes-test-schema/categories/B/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

Certain data items that are stored in the journal schema need to be brought through to the test schema so that they can be stored for use later in the app and can be included in TARS interface feeds.

Add Journal Data to Test Schema

---

mes-test-schema/categories/B/index.d.ts
mes-test-schema/categories/B/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

Refactor the Cat B test schema to create objects for each manoeuvre and separate out Controlled Stop.
Generate types for independentDriving and identification.

MES-2168: Test schema - refactor manoeuvres

---

mes-journal-schema/Journal.d.ts
mes-journal-schema/package-lock.json
mes-journal-schema/package.json
mes-journal-schema/schema-examiner-work-schedule.json
mes-test-schema/categories/B/index.d.ts
mes-test-schema/categories/B/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

* Include `examinerVisiting`, candidate's `dateOfBirth`, `gender` and `ethnicOriginCode`, examiner's `invididualId` in the journal schema + test schema
* Add a new captured field to test schema, accompaniment by `interpreter`
* Bump to `@dvsa/mes-journal-schema@1.0.7` and `@dvsa/mes-test-schema@1.0.21`

MES-2591/2592: Update test and journal schemas to include fields for RSIS

---

mes-journal-schema/Journal.d.ts
mes-journal-schema/package-lock.json
mes-journal-schema/package.json
mes-journal-schema/schema-examiner-work-schedule.json
mes-test-schema/categories/B/index.d.ts
mes-test-schema/categories/B/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

* Use `ethnicityCode` instead of `ethnicOriginCode` in `candidate` details
* Replace `vehicleSlotType` with `vehicleTypeCode` in `testSlot`s and `advanceTestSlot`s
* Bump to `@dvsa/mes-journal-schema@1.0.8` and `@dvsa/mes-test-schema@1.0.23`.

MES-2809: RSIS schema enhancements

---

mes-search-schema/index.d.ts
mes-search-schema/index.json
mes-search-schema/package.json
mes-test-schema/categories/B/index.d.ts
mes-test-schema/categories/B/index.json
mes-test-schema/package.json

- Updated `applicationReference` in searchResult schema to be a number instead of string
- Capitalised all enum values in the `specialNeedsCode` (Szabi requested to combine)

MES-2954 - Change application reference from string to number

---

mes-test-schema/categories/B/index.d.ts
mes-test-schema/categories/B/index.json
mes-test-schema/package.json

Link to bug - https://jira.dvsacloud.uk/browse/MES-3111
Terminating the test on the CCP where no email is provided and post is not selected - i.e. "By email (new email)" is preselected and no new email is entered. 
Throws the following error
`2019-08-02T13:29:55.897Z 52f1981c-412e-405c-bb13-8fdd8cd013d3 Could not validate the test result body ValidationError: child "communicationPreferences" fails because [child "communicationMethod" fails because ["communicationMethod" is required]]`
Fixed by adding a `Not provided` option to the `communicationMethod` and `conductedLanguage` enums to cover this scenario, at the moment it is defaulted to `null`.
Accompanying mobile app change PR - https://github.com/dvsa/mes-mobile-app/pull/673

MES-3111 - Fix for when terminating test on CCP page and there is no default email, the upload fails validation

---

mes-test-schema/package-lock.json
mes-test-schema/package.json

Incorrectly set version number in package.json (should have done npm version minor to increment it prior to publishing). 
This brings the package.json version number in line with the npm versions

set version number to npm version

---

mes-test-schema/categories/B/index.json
mes-test-schema/categories/B/partial.d.ts
mes-test-schema/categories/B/partial.json
mes-test-schema/categories/BE/index.json
mes-test-schema/categories/BE/partial.d.ts
mes-test-schema/categories/BE/partial.json
mes-test-schema/categories/Common/index.d.ts
mes-test-schema/categories/Common/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

Creating a common definition for QuestionResult and referencing that for ShowMe/TellMe Questions in vehicle checks.

MES-3926: Creating QuestionResult definition

---

mes-test-schema/categories/BE/index.d.ts
mes-test-schema/categories/BE/index.json
mes-test-schema/categories/BE/partial.d.ts
mes-test-schema/categories/BE/partial.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

- Removing `code78Present` for Category B+E
- Removing `PassCompletion` from `index.d.ts`

MES-4239: Removing code 78 for Category B+E

---

mes-test-schema/categories/B/index.json
mes-test-schema/categories/BE/index.json
mes-test-schema/categories/common/index.d.ts
mes-test-schema/categories/common/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

- Adds the `"additionalProperties": false` key to the `TestSummary` interface in order to prevent anonymous properties being added into the test result.

prevent additional anonymous properties

---

mes-test-schema/categories/B/index.json
mes-test-schema/categories/BE/index.json
mes-test-schema/categories/common/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

- Adds the `type` key to the `questionResult` definition in the common json schema.
- Generates the new category specific json schemas.
Addresses the following error seen in dev which was causing vehicle checks validation to be bypassed -
```
2019-12-09T10:36:15.806Z    1e3ba2cf-50e7-4248-86bd-5adcd37595e2    WARN    WARNING: schema missing a 'type' or '$ref' or 'enum': 
{
"description": "Result of a vehicle checks question",
"additionalProperties": false,
"properties": {
"code": {
"$ref": "#/definitions/questionCode"
},
"description": {
"$ref": "#/definitions/questionDescription"
},
"outcome": {
"$ref": "#/definitions/questionOutcome"
}
}
}
```

Fix vehicle checks for enjoi

---

mes-test-schema/categories/index.d.ts

Extending the `TestResultSchemasUnion` with `TestResultCatAM1Schema` & `TestResultCatAM2Schema`

MES-4633: Adding AM1 and AM2 TestResults to the Union

---

mes-test-schema/categories/AM2/index.d.ts
mes-test-schema/categories/AM2/index.json
mes-test-schema/category-definitions/AM2/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

Bug of MES-4402
Included EyeSight Check into the TestData type
Removed Mod1 certificate number from Mod2; replaced with DL196CBTCertNumber

Fixes to Mod2 Schema missing eyesight and CBT cert

---

mes-test-schema/categories/AM1/index.json
mes-test-schema/categories/AM2/index.json
mes-test-schema/generateSchemas.ts
mes-test-schema/package-lock.json
mes-test-schema/package.json

- Adds new function to de-reference json schema files
- Resolves issue for Mod 1 and 2 where schemas containing references to external files cause errors when passing to enjoi for validation. 
- **Note:** The categories/AM1.index.json and categories/AM1.index.json have been fully regenerated as standalone schemas (dereferenced from the common schema) as a result of this change, hence the 6k or so lines added

MES-4803 de-reference Mod1 and Mod2 schemas.

---

mes-test-schema/categories/AM1/index.d.ts
mes-test-schema/categories/AM1/index.json
mes-test-schema/category-definitions/AM1/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

- Updates mod 1 to add single fault competencies and comments
- Adds comments field to existing emergencyStop and avoidance competencies

MES-4810 updated single fault competencies

---

mes-test-schema/categories/AM1/index.d.ts
mes-test-schema/categories/AM1/index.json
mes-test-schema/category-definitions/AM1/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

- `provisionalLicenceProvided` is not relevant to Mod 1, this breaks validation so has been removed.

MES-4800 - Removes provisionalLicenceProvided from mod 1

---

mes-test-schema/categories/AM1/index.d.ts
mes-test-schema/categories/AM1/index.json
mes-test-schema/category-definitions/AM1/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

Changes the speed requirement in CAT A mod 1, by removing the emergency stop and avoidance into single fault types.

New speed requirement types MES-4963

---

mes-test-schema/package-lock.json
mes-test-schema/package.json

The current version is 3.19.2, however, a 3.20.0 and 3.20.1 have been published and deprecated.
Bumps to 3.20.2 which is the newest version number

Core: test schema version inconsistent with npmjs

---

mes-test-schema/categories/ADI2/index.d.ts
mes-test-schema/categories/ADI2/index.json
mes-test-schema/categories/ADI2/partial.d.ts
mes-test-schema/category-definitions/ADI2/partial.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

Add 3 new fields to schema to capture newly identified ADI PT2 data:
- orditTrainedCandidate
- trainerRegistrationNumber
- trainingRecords

MES-5204  - ORDIT / Trainer Reg Number / Training Records

---

mes-test-schema/categories/ADI2/index.json
mes-test-schema/categories/AM1/index.d.ts
mes-test-schema/categories/AM1/index.json
mes-test-schema/categories/AM2/index.d.ts
mes-test-schema/categories/AM2/index.json
mes-test-schema/categories/B/index.json
mes-test-schema/categories/BE/index.json
mes-test-schema/categories/C/index.json
mes-test-schema/categories/C1/index.json
mes-test-schema/categories/C1E/index.json
mes-test-schema/categories/CE/index.json
mes-test-schema/categories/CPC/index.d.ts
mes-test-schema/categories/CPC/index.json
mes-test-schema/categories/D/index.json
mes-test-schema/categories/D1/index.json
mes-test-schema/categories/D1E/index.json
mes-test-schema/categories/DE/index.json
mes-test-schema/categories/F/index.json
mes-test-schema/categories/G/index.json
mes-test-schema/categories/H/index.json
mes-test-schema/categories/K/index.json
mes-test-schema/categories/common/index.d.ts
mes-test-schema/categories/common/index.json
mes-test-schema/category-definitions/AM1/index.json
mes-test-schema/category-definitions/AM2/index.json
mes-test-schema/category-definitions/CPC/index.json
mes-test-schema/category-definitions/common/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

https://jira.dvsacloud.uk/browse/MES-5733
- Updates `examinerBooked` and `examinerConducted` keys to be number OR string to accommodate delegated examiners' alphanumeric examinerIds.

Mes 5733 - Allow alphanumeric delegated examiner ID

---

mes-test-schema/categories/ADI2/index.json
mes-test-schema/categories/B/index.json
mes-test-schema/categories/BE/index.json
mes-test-schema/categories/C/index.json
mes-test-schema/categories/C1/index.json
mes-test-schema/categories/C1E/index.json
mes-test-schema/categories/CE/index.json
mes-test-schema/categories/CPC/index.json
mes-test-schema/categories/D/index.json
mes-test-schema/categories/D/partial.d.ts
mes-test-schema/categories/D1/index.json
mes-test-schema/categories/D1/partial.d.ts
mes-test-schema/categories/D1E/index.json
mes-test-schema/categories/D1E/partial.d.ts
mes-test-schema/categories/DE/index.json
mes-test-schema/categories/DE/partial.d.ts
mes-test-schema/categories/F/index.json
mes-test-schema/categories/G/index.json
mes-test-schema/categories/H/index.json
mes-test-schema/categories/K/index.json
mes-test-schema/categories/common/index.d.ts
mes-test-schema/categories/common/index.json
mes-test-schema/category-definitions/D/partial.json
mes-test-schema/category-definitions/D1/partial.json
mes-test-schema/category-definitions/D1E/partial.json
mes-test-schema/category-definitions/DE/partial.json
mes-test-schema/category-definitions/common/index.json
mes-test-schema/package-lock.json
mes-test-schema/package.json

Removing safetyQuestions
Removing safetyQuestionResult
from cat D, D1, DE, D1E and common
Bumping version number.
> Not entirely sure why does GitHub recognise `mes-test-schema/categories/ADI2` and `mes-test-schema/categories/CPC` that the entire file changed. In reality only a few lines changed in both files. Here are some screenshots of VSCode to demonstrate it:
> ![Screenshot 2020-11-24 at 15 37 49](https://user-images.githubusercontent.com/7311745/100119874-43486e80-2e6f-11eb-9cfe-1cebdd6d6802.png)
> ![Screenshot 2020-11-24 at 15 38 31](https://user-images.githubusercontent.com/7311745/100120008-6410c400-2e6f-11eb-8e20-b943b6ace0d0.png)

Mes-6084: Remove safety questions
